language: ruby
rvm:
- 2.4.1
stages:
- build
- test
- before_deploy
- deploy
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: S57Olpsly/QGmzgwfLrrvyx1IVsht5cS0RAn/FgN4OySm+cN/bGomS5ED1/UEDgymO5RAgtsYsOZRqQjQMtZKRkntNxMuukrQjn2nHElozHYqsrL3y6uxgA4+pIH4xjDaPsylZ+KG9DIpCKk/UDmDqpvcS1QenJDb2fHOldlYfYCJ0ceOyKoJvD77+ra+7z5IffCnG2honNLDEktNsGnxvkvt6iw3/sanRb/K3OKtOReC44J1cN2PHdRYrcsTQkn49AuQNHjzs0oLcHClUxIyjjS7xjvVOZjJf7erfV8DGIIx+QRAWEFjM/0kI5T8K4p3mxNBJpE2wqz8Fx3KN6HWdsf+3kos0ksTKekg9yQ2yFNvI1EVwW1loQBNLUIh4fzMmhYWLnvxR+F51ecfamDsc8yOopTCPar0zNEkhMmH1AJPgn3hJtBvPKyfwrao30ql7uHJlFAWWVY193zZJ0pg6xafwV10xi6n+DBcRTeliXsOxNuJKQcJ+1Pwo1/Ba5EN1FEJaB/CgxbKlblxO+oJWRLF7aXFOGmvh968szZ3jVmp+cERz8sBaC84UaKE2qWwHVKCUOvmlKRwWGXNifscMPN1zF4IjNhCXo41D/Dzm6MZkynKXpSxXRoIuBseWOs3cb86L8W4Zrpr6mm28glaTlGaZtXvwlOLYFD8vPykEg=
  - secure: LFVGYcn9iCfCTl4Tcdc6KrpclaYdNnqexiNhd4VzlhppKshNxS/cpJZXT74QVrp263Gt9/XJyDw9Kzkkl/9EplGdc8fjTtBuIz/E8/0RfmXTfLUU09gSLnm136SXv/KnZkWMSKz6mUTIl0v0NpXsxzEtJGHh+KwVR6R548VCws+/2dX8WyoBhMhCg+vlenHC52bhXSBO8fOB/tTRTRl+Vwcc71B8GkyhKbvGFECnyXp5Cf7XWTQEZ4nzg1NXyM8YEeXyvMuZpEp0Vfd4gRfB8ml2WLzrQ3IDcVIwQNFbkECmwcTBBGbPccHah3Hm30g76kmgpoKBzhMGKyuJap3VjZ9Q/iUICURALAzm9XaUPk5LIN/uoUGkqwX+Fkk8Hp5A4YWe4wNmb1mXSs+8ZQdP/84LwHNw0Nd8kNTR0t/8SQ7JtfPAeTCgE1NiHHYha9kRqJgyW4rwJEnznHEFZ359Py0wpUuTRo+R7ItIbgHYFR78OqGBJJ7jNCvQS385C0VhrU0tZcQLILViRcQ+c6ieipraVfocXD4kgJTGEl8rcTdOSX15pTiAiT3AXoBD3mwjkJfQu8/j1XNtN+GjxyL3/0SBFsWAsxsmtd41IADX3yEFOVvocH3TYsJSOZbCoB8Pf1HhbdQlcFCJfD2g2lcpeoOyO0BHdMA2rOXU165rAoo=
  - secure: nk3WBTZBru1hTmllzAJu1mQcEcWb9mAwgooea0OphAlFciQvdI9SGOKrW8s4sogWC8Q7YCXQCdMMzmR3V95hjW2pMZdPNSC32WEL1Z4bmXrarZlIB5q6ifnKcj94QTBiplNDFb+njo9nIqSuZKBqf2lNgZcJf5bFUekUKfrb5gsoxB/rAPr5lcoXpkmHwDGVLrQGrv34BBFzxwhKVZg/rh49S1NckujyYu8o1O5flC/awbY7h1O25QNaHugMBvon88s0g1uxMnXT7nAKTjwMKBOMJX1UpdvPIbIqYwuKulkZsnhS53NjnGZ4UkLg3p4dZK0G164u57WnYFb3F2L+FYIJW9ueAvFIcIQwwM1zDzfzFYV+tjyKstRPNywAMbiAwH+1wKQSyNZ9BQzr3qlJ1cwwYgEVf31p+dNQDbwsk/n3lPMFhcgZ0R32ra6Bf1OL3Aeu8QQw2NnCMlE8rKbNr3Up5BXR4wBDkmfNXzoppJiGpEIgnmtiFFRA+zdCXnd4ah3dCP20AI/l+B318LOU0/Tch5IMpqSZUbnq6MaAcEGzyp/Z4OPqs1Nd+8Ov/3IQs0z+5fIIVOi/uRCX50760W5zZSWKb2jhyUCDOM47H0xtIPyq5YUnd5THMMFkibrAeV8vKReQ9RHoEqxT3RRpiDRKVZyQezQErsB4jBSlJRo=
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
sudo: false
cache: bundler
notifications:
  email: false
build:
  script: bundle exec jekyll build
test:
  script: bundle exec htmlproofer --disable-external --assume-extension --empty-alt-ignore
    ./_site
before_deploy:
- openssl aes-256-cbc -K $encrypted_136c573afebc_key -iv $encrypted_136c573afebc_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet --delete-after _site/ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DIRECTORY
  on:
    branch: master
