_id: 3e356630-9feb-11eb-9fd0-9135de37825c
name: Harry
message: >-
  This post has been incredibly helpful. We are currently switching to netlify
  and this has been my working guide and a godsend. Thank you!
date: 1618711827
