_id: 1ed03bc0-96e2-11ea-9d20-b12befb1d3af
name: Alexdelli
message: "Hi Andreas, I find your blog searching for synology docker, and I find The post about migrating to Netlify (what I’m doing since two weeks ago.\r\nNow your blog is in my favourite bar"
date: 1589570851
